$background = 0b0f11
$onBackground = dfe6ee
$surface = 0b0f11
$surfaceDim = 0b0f11
$surfaceBright = 262d33
$surfaceContainerLowest = 000000
$surfaceContainerLow = 0f1417
$surfaceContainer = 151a1e
$surfaceContainerHigh = 1a2025
$surfaceContainerHighest = 20272c
$onSurface = dfe6ee
$surfaceVariant = 20272c
$onSurfaceVariant = a5acb3
$outline = 6f767d
$outlineVariant = 42494f
$inverseSurface = f8f9fd
$inverseOnSurface = 525559
$shadow = 000000
$scrim = 000000
$surfaceTint = a7cbe7
$primary = a7cbe7
$primaryDim = 99bdd9
$onPrimary = 1f445b
$primaryContainer = 33566e
$onPrimaryContainer = c9e7ff
$inversePrimary = 40637b
$primaryFixed = bde1fe
$primaryFixedDim = afd3ef
$onPrimaryFixed = 193f56
$onPrimaryFixedVariant = 385c74
$secondary = b7c9d8
$secondaryDim = a9bbca
$onSecondary = 31424f
$secondaryContainer = 2c3d4a
$onSecondaryContainer = afc2d1
$secondaryFixed = d2e5f5
$secondaryFixedDim = c4d7e7
$onSecondaryFixed = 30414e
$onSecondaryFixedVariant = 4c5e6b
$tertiary = d4d7ff
$tertiaryDim = c4c9f8
$onTertiary = 444a71
$tertiaryContainer = c4c9f8
$onTertiaryContainer = 3c4168
$tertiaryFixed = c4c9f8
$tertiaryFixedDim = b6bbe9
$onTertiaryFixed = 282d53
$onTertiaryFixedVariant = 454a72
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = 587b94
$secondaryPaletteKeyColor = 687987
$tertiaryPaletteKeyColor = 6f749e
$neutralPaletteKeyColor = 74777a
$neutralVariantPaletteKeyColor = 71787f
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = 587b94
$secondary_paletteKeyColor = 687987
$tertiary_paletteKeyColor = 6f749e
$neutral_paletteKeyColor = 74777a
$neutral_variant_paletteKeyColor = 71787f
$term0 = 343434
$term1 = 8383ff
$term2 = 44def5
$term3 = 75fcdd
$term4 = 7fb1cc
$term5 = 85abed
$term6 = 87d4ee
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 89ecff
$term11 = c9fff3
$term12 = a7c5d4
$term13 = a4bff7
$term14 = 99e6ff
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = cbdeff
$mauve = 91c4ff
$red = 8cb4ff
$maroon = abbef0
$peach = e0c2f9
$yellow = d0f9f4
$green = abe9ff
$teal = b6e7ff
$sky = b1e2ff
$sapphire = 87d0fd
$blue = 7bc4fc
$lavender = a2d1ff
$klink = 328fc4
$klinkSelection = 318fc4
$kvisited = 2c83d7
$kvisitedSelection = 2a83d7
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 00b8e0
$kpositiveSelection = 00b8e0
$text = dfe6ee
$subtext1 = a5acb3
$subtext0 = 6f767d
$overlay2 = 61676d
$overlay1 = 52585d
$overlay0 = 444a4e
$surface2 = 373c40
$surface1 = 292e31
$surface0 = 1a1e21
$base = 0b0f11
$mantle = 0b0f11
$crust = 0a0e10
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
